youtube-clone-fullstack-python-django-ajax-master/youtube/youtube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtube_app.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name="index"),
    path('youtube/video/<int:id>', views.videoplayback,name="playback"),
    path('youtube/category/<str:slug>', views.category,name="category"),
    path('youtube/search-suggestion', views.search_suggestions,name="search-suggestions"),
    path('youtube/search/<param>', views.search,name="search"),
    path('youtube/signup', views.handlesignup,name="signup"),
    path('youtube/logout', views.handlelogout,name="logout"),
    path('youtube/login', views.handlelogin,name="signin"),
    path('youtube/watchlater/<int:id>', views.watchlater,name="watchlater"),
    path('youtube/watchlater-list', views.show_watch_later,name="watchlater"),
    path('youtube/watchlater/remove/<int:id>', views.remove_watch_video,name="remove_watchlater"),
    path('youtube/history', views.history_show,name="history_show"),
    path('youtube/history/remove/<param>', views.history_remove,name="history_remove"),
    path('youtube/history/remove/1abc745bf-g', views.history_remove,name="history_remove"),
    path('youtube/like/<int:id>', views.like_update,name="like"),
    path('youtube/dislike/<int:id>', views.dislike_update,name="dislike"),
    path('youtube/user-upload', views.user_upload,name="userupload"),
    path('youtube/user-upload/submit', views.submit_user_upload,name="useruploadsubmit"),
    path('youtube/user-channel/videos', views.videos_user_upload,name="showupload"),
    path('youtube/uservideo/<int:id>', views.user_video_playback,name="userplayback"),
    path('youtube/uservideo/remove/<int:id>', views.user_video_remove,name="uservideoremove"),
    path('youtube/comment/<int:video_id>', views.add_comment,name="add_comment"),
    path('youtube/reply/<int:id>', views.reply_comment,name="reply_comment"),
    path('youtube/deletecomment/<int:parent_id>', views.delete_parentcomment,name="delete_parentcomment"),
    path('youtube/deletecomment/child/<int:child_id>', views.delete_childcomment,name="delete_childcomment"),
]

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/models.py
from django.db import models
from django.contrib.auth.models import User



class video_details(models.Model):
    video_id=models.AutoField(primary_key=True)
    video_title=models.CharField(max_length=150)
    video_category=models.CharField(max_length=100)
    video_description=models.TextField(default="")
    video_thumbnail=models.ImageField(upload_to='thumbnail')
    video_channelname=models.CharField(max_length=100,default="")
    video_timestamp=models.DateTimeField(auto_now_add=True)
    video_duration=models.CharField(max_length=20,default="")
    video_views=models.IntegerField(default=0)
    video_videofile=models.FileField(upload_to='video')
    def __str__(self):
        return self.video_title
    
class watch_later(models.Model):    
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    videos=models.ForeignKey(video_details,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username
    
    
class like(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    video=models.ForeignKey(video_details,on_delete=models.CASCADE)    
    total_like=models.IntegerField(default=0)
    def __str__(self):
        return self.user.username
    
class dislike(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    video=models.ForeignKey(video_details,on_delete=models.CASCADE)    
    total_dislike=models.IntegerField(default=0)
    def __str__(self):
        return self.user.username
    
class user_uploads(models.Model):
    video_id=models.AutoField(primary_key=True)
    user=models.ForeignKey(User,null=True, blank=True,on_delete=models.CASCADE)
    video_title=models.CharField(max_length=150)
    video_category=models.CharField(max_length=100)
    video_description=models.TextField(default="")
    video_thumbnail=models.ImageField(upload_to='thumbnail')
    video_timestamp=models.DateTimeField(auto_now_add=True)
    video_duration=models.CharField(max_length=20,default="")
    video_views=models.IntegerField(default=0)
    video_videofile=models.FileField(upload_to='video')
    def __str__(self):
        return self.user.username
    
class user_videos_history(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)    
    videos=models.ForeignKey(video_details,on_delete=models.CASCADE)
    timestamp=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username+self.videos.video_title
    
    
class comments(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    video=models.ForeignKey(video_details,on_delete=models.CASCADE)
    content=models.TextField()
    timestamp=models.DateTimeField(auto_now_add=True)
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True, blank=True)  
    def __str__(self):
        return f"Comment By {self.user.username}-{self.content}"

   
        
    


# Create your models here.

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/forms.py
from django import forms
from .models import user_uploads

class user_files_Form(forms.ModelForm):
    class Meta:
        model=user_uploads
        fields=['video_title', 'video_category', 'video_description', 'video_thumbnail','video_duration', 'video_videofile']

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/views.py
import json

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.utils import timezone

from .forms import user_files_Form
from .models import video_details, watch_later, user_videos_history, like, dislike, user_uploads, comments


def index(request):
    videos=video_details.objects.all()
    form=user_files_Form()
    return render(request,'youtube_app/index.html',{'videos':videos,'form':form})

def videoplayback(request, id):
    play_video = get_object_or_404(video_details, video_id=id)
    max_like=0
    max_dislike=0
    # Update video views count
    play_video.video_views += 1
    play_video.save()
    
    right_videos = video_details.objects.exclude(video_id=id)
    user_liked = False
    user_disliked = False
    is_parent_comments = comments.objects.filter(video=play_video, parent=None).exists()
    
    if request.user.is_authenticated:
        # in history video present
        his_check=user_videos_history.objects.filter(user=request.user,videos=play_video).exists()
        if his_check:
            update_timestamp=user_videos_history.objects.filter(user=request.user,videos=play_video).first()
            update_timestamp.timestamp=timezone.now()
            update_timestamp.save()
        else:
            insert_video=user_videos_history(user=request.user,videos=play_video) 
            insert_video.save()   
        
        user_liked = like.objects.filter(user=request.user, video=play_video).exists()
        user_disliked = dislike.objects.filter(user=request.user, video=play_video).exists()
        
        # Check if user liked or disliked the video
    
    total_likes=like.objects.filter(video=play_video).exists()
    total_dislikes=dislike.objects.filter(video=play_video).exists()
    
    # Get total likes and dislikes for the video
    if total_likes:
        most_like=like.objects.filter(video=play_video).order_by('-total_like').first()
        max_like=most_like.total_like
    if total_dislikes:
        most_dislike=dislike.objects.filter(video=play_video).order_by('-total_dislike').first()
        max_dislike=most_dislike.total_dislike
        
    
    # Fetch parent comments and their replies
    parent_comments = comments.objects.filter(video=play_video, parent=None).order_by('-timestamp')
    
    return render(request, 'youtube_app/playback.html', {
        'video': play_video,
        'right_videos': right_videos,
        'total_like': max_like,
        'total_dislike': max_dislike,
        'like_status': user_liked,
        'dislike_status': user_disliked,
        'parent_comments': parent_comments,
    })
      
    



def category(request,slug):
    if slug=="All":
        return redirect('/')
    else:
     match_videos=video_details.objects.filter(video_category=slug)
     return render(request,'youtube_app/category.html',{'match_videos':match_videos})
 
def search_suggestions(request):
    if request.method == 'GET':
        query = request.GET.get('query', '')
        search_suggestions=video_details.objects.filter(Q(video_title__icontains=query)|Q(video_category__icontains=query)|Q(video_channelname__icontains=query))
        search_suggestions_list = list(search_suggestions.values())
        response = json.dumps(search_suggestions_list ,default=str)
        return HttpResponse(response)
    
def search(request,param):
    try:
        param = int(param)
        search = video_details.objects.filter(video_id=param)
    except ValueError:
        query = request.GET.get('search', '')
        search = video_details.objects.filter(
            Q(video_title__icontains=query) |
            Q(video_category__icontains=query) |
            Q(video_channelname__icontains=query)
        )
    return render(request,'youtube_app/index.html',{'videos':search})
        
def handlesignup(request):
    if request.method=="POST":
     try:
        fname=request.POST.get('signupfname')
        lname=request.POST.get('signuplname')
        uname=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        myuser=User.objects.create_user(uname,email,password)
        myuser.first_name=fname
        myuser.last_name=lname
        myuser.save()
        login_user=authenticate(request,username=uname,password=password)
        if login_user is not None:
            login(request,login_user)
        messages.success(request,"Account Created Successfully")
        return redirect(request.META.get('HTTP_REFERER', '/'))
     except:
         messages.error(request,"Account already Exist")
         return redirect(request.META.get('HTTP_REFERER', '/'))
    else:
        return HttpResponse('404 Verification Failed')    
       
def handlelogout(request):
    if request.user.is_authenticated:
        logout(request)        
        return redirect('/')
    else:
        return HttpResponse('User Not Found')
    
def handlelogin(request):
    if request.method=="POST":    
        luname=request.POST.get('loginusername')
        lpassword=request.POST.get('loginpassword')
        user=authenticate(request,username=luname,password=lpassword)
        if user is not None:
            login(request,user)
            return redirect(request.META.get('HTTP_REFERER', '/'))
        else:
            messages.error(request,"Wrong Credentials Try Again")    
            return redirect(request.META.get('HTTP_REFERER', '/'))
    
    else:
        return HttpResponse("404 Request Failed")    

        
def watchlater(request,id):
    if request.user.is_authenticated:
        get_video=video_details.objects.filter(video_id=id).first()
        is_video_added=watch_later.objects.filter(user=request.user,videos=get_video).exists()
        if not is_video_added:
         save_video=watch_later(user=request.user,videos=get_video)
         save_video.save()   
         return JsonResponse({'success':True})  
        else:
            return JsonResponse({'success':True}) 
    else:
        messages_json=[]
        messages.error(request,"Login Required For Add To Watch Later")
        for message in messages.get_messages(request):
            messages_json.append({
                'message':message.message,
                'tags':message.tags,
            })
        return JsonResponse({'success': False, 'messages': messages_json}) 
                       
    
def show_watch_later(request):
    if request.user.is_authenticated:
        watch_later_videos=watch_later.objects.filter(user=request.user)
        return render(request,'youtube_app/watchlater.html',{'videos':watch_later_videos})    
    else: 
        messages.error(request,"Login Required")
        return redirect(request.META.get('HTTP_REFERER', '/'))  
    
def remove_watch_video(request,id):
    if request.user.is_authenticated:
        del_video=watch_later.objects.filter(user=request.user,videos=id).delete()
        return JsonResponse({'success':True})
    else:
        messages_json=[]
        messages.error(request,"Something Went Wrong")
        for message in messages.get_messages(request):
            messages_json.append({
                'message':message.message,
                'tags':message.tags,
            })
        return JsonResponse({'success': False, 'messages': messages_json}) 
       
def history_show(request):
    if request.user.is_authenticated:
        his_video=user_videos_history.objects.order_by('-timestamp')
        return render(request,'youtube_app/history.html',{'videos':his_video})
    else:
        messages.error(request,"Login Required")
        return redirect(request.META.get('HTTP_REFERER', '/'))      
             
             
def history_remove(request,param):
    if param =="1abc745bf-g":
        if request.user.is_authenticated:
         user_videos_history.objects.filter(user=request.user).delete()
         return redirect(request.META.get('HTTP_REFERER', '/'))
    if request.user.is_authenticated:
        get_video=video_details.objects.filter(video_id=param).first()
        user_videos_history.objects.filter(user=request.user,videos=get_video).delete()
        return JsonResponse({'success':True})
    else:
         messages_json=[]
         messages.error(request,"Something Went Wrong")
         for message in messages.get_messages(request):
            messages_json.append({
                'message':message.message,
                'tags':message.tags,
            })
         return JsonResponse({'success': False, 'messages': messages_json}) 
          
def like_update(request,id):
    if request.user.is_authenticated:
        final_like=0
        final_dislike=0
        get_id_video=video_details.objects.filter(video_id=id).first()
        is_user_disliked_video=dislike.objects.filter(user=request.user,video=get_id_video).exists()
        if is_user_disliked_video:
            #del user from dislike and update final_dislike
            get_most_dislike=dislike.objects.filter(video=get_id_video).order_by('-total_dislike').first()
            final_dislike=get_most_dislike.total_dislike-1
            get_most_dislike.total_dislike=get_most_dislike.total_dislike-1
            get_most_dislike.save()
            rem_user_from_disliked=dislike.objects.filter(user=request.user,video=get_id_video).delete()
            #check whether video is in liked or not
            check_file_in_like=like.objects.filter(video=get_id_video).exists()
            if check_file_in_like:
                #if present getting max like of video to update final like
                get_max_like=like.objects.filter(video=get_id_video).order_by('-total_like').first()
                final_like=get_max_like.total_like+1
                #setting user

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/templates/youtube_app/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load custom_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/basic.css'%}">
    <link rel="icon" type="image/png" href="{%static 'img/logo.png'%}">
    {%block css%}{%endblock%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6ff5ef7611.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js" ></script>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css" rel="stylesheet">
    <title>{%block title%}MEMtube{%endblock%}</title>
</head>
<body>
 <div class="navbar">
<div class="logo-container">
  <div class="logo-hamburger">
    <i class="fa-solid fa-bars" id="hamburger-open-close" onclick="hamburger()" ></i>
    <a href="/"><img src="{%static 'img/logo.png'%}"></a>
    <a href="/"><h2>MEMTube</h2></a>
  </div>
</div>
<div class="search-container">
    <form action="/youtube/search/query" method="GET">
        <input type="text" name="search" id="search" autocomplete="off"
        placeholder="Search" >
        <div class="search-result">
            <ul id="search-suggestions">
                
            </ul></div>
        <button type="submit"><i class="fa-solid fa-magnifying-glass" ></i></button>
    </form>
</div>
<div class="profile-container">
       {% if user.is_authenticated%}
       <a href="/youtube/user-upload"><i class="fa-solid fa-upload" ></i></a>
       <div class="dropdown">
           <img src="{%static 'img/user.png'%}" class=" dropdown-toggle"  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
        <div class="dropdown-menu" id="logo-dropdown" aria-labelledby="dropdownMenuButton">
          <h5 class="dropdown-item">Welcome ,{{user.first_name}}</h5>
          <a class="dropdown-item" href="/youtube/user-channel/videos">My Channel</a>
          <a class="dropdown-item" href="/youtube/user-upload">Upload Video</a>
          <a class="dropdown-item" href="/youtube/logout">Logout</a>
        </div>
      </div>
        {%else%}
    <button class="signin" data-bs-toggle="modal" data-bs-target="#loginModal"><i class="fa-solid fa-user"></i>Sign in</button>
    {%endif%}
    
</div>
 </div>
 
 <!--signup Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="signupModalLabel">Sign Up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="/youtube/signup" method="post">{% csrf_token %}
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">First Name:</label>
              <input type="text" class="form-control" name="signupfname" required  placeholder="Enter First Name">
            </div>
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Last Name:</label>
              <input type="text" class="form-control" name="signuplname" required  placeholder="Enter Last Name">
            </div>
  
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Username:</label>
            <input type="text" class="form-control" name="username" required  placeholder="Choose Username(alphanumeric only)">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address:</label>
            <input type="email" class="form-control" name="email"  placeholder="name@example.com" required>
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Password:</label>
            <input type="password" class="form-control"  name="password" placeholder="Enter Your Password" required>
          </div>
          <div class="mb-3">
            <button type="submit" class="btn btn-primary">Signup</button>
          </div>
          </form>
      </div>
      <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">
            Login
            </button>
        </div>
      </div>
    </div>
  </div>
<!--login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="loginModalLabel">Sign Up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <form action="/youtube/login" method="post">{%csrf_token%}
            <label for="exampleFormControlInput1" class="form-label">Username:</label>
            <input type="text" class="form-control" name="loginusername" required  placeholder="Username">
          
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Password:</label>
            <input type="password" class="form-control"  name="loginpassword" placeholder="Enter Your Password" required>
          </div>
          <div class="mb-3">
            <button type="submit" class="btn btn-primary">Login</button>
          </div>
        </form>
      </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#signupModal">
            Signup
            </button>
        </div>
      </div>
    </div>
  </div>


<!-- body content -->

<div class="body-container">
    
    <div class="sidebar" >
        <div class="sidebar-items">
            <a href="/" class="sidebar-item"><i class="fa-solid fa-house"></i>Home</a>
            <hr>
            <a href="/youtube/history" class="sidebar-item"><i class="ri-links-line"></i>History</a>
            <a href="/youtube/watchlater-list" class="sidebar-item"><i class="fa-solid fa-video"></i>Watch Later</a>
            <hr>
            <h4>Explore:</h4>
            <a href="/youtube/category/Music" class="sidebar-item"><i class="fa-solid fa-music"></i>Music</a>
            <a href="/youtube/category/Body-Building" class="sidebar-item"><i class="fa-solid fa-dumbbell"></i>Workout</a>
            <a href="/youtube/category/Computer Programming" class="sidebar-item"><i class="fa-solid fa-laptop"></i>Programming</a>
            <a href="/youtube/category/News" class="sidebar-item"><i class="fa-solid fa-newspaper"></i>News</a>
            <a href="/youtube/category/Ajax" class="sidebar-item"><i class="fa-solid fa-chalkboard"></i>Learning</a>
            <hr>
               {%if user.is_authenticated%}
                <a href="/youtube/user-channel/videos"  class="sidebar-item"><i class="fa-solid fa-tv"></i>Your Channel</a>
                {%else%}
               <span class="side-login"><i class="fa-solid fa-user"></i>
                <button class="signin" data-bs-toggle="modal" data-bs-target="#loginModal">Sign in</button></span>
                {%endif%}
            </div>
        </div>
       
        {%block playback%}{%endblock%}
     {%block index%}{%endblock%}
     {%block watchlater%}{%endblock%}
     {%block history%}{%endblock%}
     {%block category%}{%endblock%}
     {%block user_section%}{%endblock%}
    

      </div>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="{%static 'js/basic.js'%}"></script>
{%block script%}


{%endblock%}
</body>
</html>

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/templates/youtube_app/category.html
{%extends 'youtube_app/basic.html'%}
{% load humanize %}
{%load static%}
{%block css%}
<link rel="stylesheet" href="{%static 'css/index.css'%}">
{%endblock%}
{%block category%}

<div class="content">
    <div class="tile-container">
       <div class="tile">
          <a href="/youtube/category/All"><p>All</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/HTML" ><p>HTML</p></a>
       </div>
       <div class="tile">
         <a href="/youtube/category/CSS"><p>CSS</p></a>
       </div>
       <div class="tile">
         <a href="/youtube/category/Body-Building"><p>Body-Building</p></a>
       </div>
       <div class="tile">
         <a href="/youtube/category/Music" ><p>Music</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/Computer Programming" ><p>Computer Programming</p></a>
       </div>
       <div class="tile">
         <a href="/youtube/category/React" ><p>React</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/Java Script" ><p>JavaScript</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/C Programming" ><p>C Programming</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/Python"><p>Python</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/Ajax"><p>Ajax</p></a>
       </div>
       <div class="tile">
        <a href="/youtube/category/Electronics"> <p>Electronics</p></a>
       </div>
       <div class="tile">
          <a href="/youtube/category/Django"><p>Django</p></a>
       </div>
       
       
    </div>
    {%if messages%}
    {%for message in messages%}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" id="closealert">
       {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {%endfor%}
    {%endif%}
    
<div class="video-container" id="video-cards">
    {%for video in match_videos%}
    <div class="video-content-cover">
       <div class="video-thumbnail">
          <a href="/youtube/video/{{video.video_id}}"><img src="{{video.video_thumbnail.url}}" ></a>
       </div>
       <div class="video-data">
          <div class="channel-logo">
             <a href=""><img src="{%static 'img/user.png'%}"></a>
          </div>
          <div class="video-title">
             <div class="title-channel">
             <a href="/youtube/video/{{video.video_id}}"><h3 class="title">{{video.video_title}}</h3></a>
             <p class="channel-name">{{video.video_channelname}}<span> ✔</span></p></div>
             <div class="views-time">
               
                <p>{{video.video_views}} views</p>
                <p class="time"><span>•</span>{{video.video_timestamp |naturaltime}}</p>
             </div>
          </div>
       </div>  
       </div>
    {%endfor%}
{%endblock%}

youtube-clone-fullstack-python-django-ajax-master/youtube/youtube_app/templates/youtube_app/user_upload.html
{%extends 'youtube_app/basic.html'%}
{%load static%}
{%block title%}Upload Video{%endblock%}
{%block css%}
<style>
    .user-form:hover::-webkit-scrollbar-thumb{
        background:#717171;
    }
    .user-form{
        width: 100vmax;
        overflow-y: scroll;
        padding-bottom: 20px;
        padding-left:10%;
        max-height:90vh ;  
    }
    .sidebar{
        position: absolute;
        max-height:87vh;
    }
    .user-form form{
        width:80%;
        
    }
    .user-form h3{
        font-size: 20px;
    }
   
    .user_upload_form{
        display:flex;
        flex-direction: column;
        padding:5px;
    }
    .user_upload_form input,.user_upload_form textarea{
        color:#fff;
        width:100%;
    }
    .user_upload_form input,.user_upload_form textarea{
        border:solid 0.2px #fff;
        padding:10px;
    }
    .user_upload_form textarea{
        height: 142px;
    }
    .user_upload_form div{
        padding-block: 10px;
    }
    .user_upload_form div label{
        color:#fff;
        font-size:17px;
    }
    .user_upload_form button{
        background-color: #3ea6ff;
        border-radius: 20px;
        border: solid 1px #3ea6ff;
        padding:10px 15px;
    }
    .user_upload_form button:hover{
        background-color: #2074bd;

    }
    #id_video_thumbnail,#id_video_videofile{
        border:none
    }
    
</style>
{%endblock%}
{%block user_section%}
<div class="user-form">
<h3> Video Details:</h3>
<form action="/youtube/user-upload/submit" method="POST" enctype="multipart/form-data" class="user_upload_form">
{%csrf_token%}
{{form.as_p}}         
<div class="submit-button">
 <button type="submit">Upload Video</button>
</div>
</form>
</div>
{%endblock%}